# Generated by Django 5.1 on 2024-08-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidaire_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
    ]
